### ISSUE TITLE
transfer feature

### ISSUE THREAD

**Issue by JKrag** [Praqma/OurDefaultGithubIssuesWorkflow#13]
`git transfer [@user]` (in old alias based style) or `phlow transfer [@user]` (in new extension).

 - push this feature branch or PR it 
 - unassign me 
 - optionally assign to other user
 - Maybe even drop a comment about the branch about branch name (not needed if PR)

**Comment by lakruzz** [comment]
currently it's available through:

```
ghi assign -u user
git phlow issue --nowip
```

**Comment by lakruzz** [comment]
Actually `share` (which shall be renamed to park in #69)  Will also implicitly mark the issue `--nowip`

**Comment by lakruzz** [comment]
Closing this for now - we will need to _re-discover_ it, if it's still necessary
