### ISSUE TITLE
Build binaries

### ISSUE THREAD

**Issue by lakruzz** [Praqma/OurDefaultGithubIssuesWorkflow#23]
One for each platform: Win, Linux, Darwin

**Comment by groenborg** [comment]
btw we just skipped windows.. The main group uses macOS, Linux

**Comment by groenborg** [comment]
With the current git2go library we need some knowledge about linking really low level C libs into the binaries. Here are some resources which could be helpful: https://github.com/sithembiso/git2go/blob/next/Makefile#L16

**Comment by groenborg** [comment]
This stackoverflow post also have som suggestestions to this problem: http://stackoverflow.com/questions/34353216/git2go-with-libssl-and-libssh2-in-single-binary
