### ISSUE TITLE
Establish steering committee 

### ISSUE THREAD

**Issue by groenborg** [Praqma/OurDefaultGithubIssuesWorkflow#29]
@simon is working - during his internship - on implementing a git extension to handle our phlow.

He will be working using our "Milestones and office hours" approach and we need to form at _steering committee_ or if you will a _reference group_ (probably a better phrase for what we're forming) .

The group will meet with Simon (typically hangouts) in the office hours (≈ 30-60 mins) Every time we wrap up a milestone ( every 7-14 days).

In the office hours we will:

- Get Simons _demo_ of the _running code_
- Do a retrospective
- Point out new backlog items to prioritize

In between office hours we will all join Simon in he slack channel, to support him in questions that pops up during the work.

I'm suggesting the the following group for now (tick the box if you accept)

- [ ] @buep [Mentor]
- [x] @JKrag [Mentor] 
- [x] @lakruzz [Product owner]
- [x] @ThaKangBaby [as potential end-user - in the concourse agent]
- [x] @praqma-thi [co-worker and mentor]
- [ ] @monaslarsen [as end-user] OR
- [x] @JasmineCrozier [as end-user]

NOTE: we need either Jasmine OR Mona - not both - Girls, you can fight it yourself :-)

**Comment by JKrag** [comment]
@lakruzz I would like to be added to the list and join the group. I have already spent quite some time today discussing architecture and implementation with @groenborg.

Also, I think I am responsible for half the ideas on the backlog :-)

**Comment by buep** [comment]
I sorry to say it, but I don't have time on this one. I would really like that, but I have two customers and a lot of other Praqma tasks....

 I'm happy with having @JKrag taking the role as he also know the flow pretty well, and feel the pains when teaching etc. 
I look forward though the replace the ugly git aliases in my shell with a real extension...

**Comment by lakruzz** [comment]
@groenborg 
The team is set:

@lakruzz, @JKrag, @praqma-thi, @JasmineCrozier and @ThaKangBaby
