### ISSUE TITLE
Describe aliases in the file

### ISSUE THREAD

**Issue by martinmosegaard** [Praqma/OurDefaultGithubIssuesWorkflow#6]
Most of the aliases are explained in the blog post, but not all.
Still, it would be nice to have a small comment on most of them describing their purpose. I have a hard time reading for example a `sed` command combined with other stuff.

**Comment by lakruzz** [comment]
We're moving away from the aliases - we have a mockup perl version (praqma/the-phlow/perl ) and @groenborg is implementing the real thing in praqma/git-phlow
