### ISSUE TITLE
MoM - 6th Gathering

### ISSUE THREAD

**Issue by lakruzz** [Praqma/OurDefaultGithubIssuesWorkflow#76]
Kamstrup, Volvo, MAN D&T

**Comment by lakruzz** [comment]
A small recap.

What choices have been made implicitly in the tool, what if we have long lived branches.

Support for different branching strategies - especially long-lived feature branches and release branches.

**Comment by lakruzz** [comment]
When we are at a brink of a release - and need to go on to the next. We need a temporary stabilization branch. as in the git-flow.

**Comment by lakruzz** [comment]
We explain how resuming work on a branch using `workon` implicitly makes a `pull --rebase`

This should be configurable.

**Comment by lakruzz** [comment]
Talking about declarative pipelines.

**Comment by lakruzz** [comment]
Windows support is required.

**Comment by lakruzz** [comment]
Dan is suggesting that `workon`should take a parameter too - we seem to agrre that the curretn implementation is better.

**Comment by lakruzz** [comment]
What happens if you  forget to `wrapup`and do `workon`+ `deliver`

**Comment by lakruzz** [comment]
We're talking about Atlassian integration.

Jira+Bitbucket

Jira+GitHub 

Volvo hasn't decided yet if they go with one on the other.

**Comment by lakruzz** [comment]
Jira is already integration with Bitbucket - so maybe it's really just a Jira integration.

**Comment by lakruzz** [comment]
How do we handle pull requests? It's required

**Comment by lakruzz** [comment]
Multiple long-lived/integration branch support is required (Samuel)

**Comment by lakruzz** [comment]
Task creating form the command line? is it relevant? Needed?

**Comment by lakruzz** [comment]
The Command line focus is kinda cool, and might help people actually use the command line better.

We're discussing  - park/share - it's needed.

**Comment by JKrag** [comment]
This whole issue moved to git-phlow repo in https://github.com/Praqma/git-phlow/issues/98
