### ISSUE TITLE
Coordinate and follow up on the usual discussion points we see around the git phlow.

### ISSUE THREAD

**Issue by buep** [Praqma/OurDefaultGithubIssuesWorkflow#77]
See for example our internal Praqma slack around the phlow, and other places.

Try to compile a setup of FAQ questions and usual discussions points around the phlow that everybody can use for explaing why, how and the background for decisions and avoid to trying to reconsider all possible arguments again over and over again.

**Comment by lakruzz** [comment]
Seems like a long time ago - for now, going forward I'm alone on this
