### ISSUE TITLE
Special chars are not handled properly

### ISSUE THREAD

**Issue by buep** [Praqma/OurDefaultGithubIssuesWorkflow#8]
`git checkout 423-Please-publish-my-blog-post-"Trust-in-docker-images" 
error: pathspec '423-Please-publish-my-blog-post-Trust-in-docker-images' did not match any file(s) known to git.`

Chars like `"` needs to be escaped:

`git checkout 423-Please-publish-my-blog-post-\"Trust-in-docker-images\" `

I propose we handle all unsafe shell chars by omitting them. Make a list of unsafe chars we handle, and a match by their replacement, defaults to nothing meaning omitting them.

I know that also `[ ` is a problem I tend to use special chars in my github issue title... once a while.

**Comment by lakruzz** [comment]
closed with commit in #41
